### ISSUE TITLE
Authorization header do no reach get_json.php

### ISSUE THREAD

**Issue by joaquinabenza** [pcca-matrix/XMRig-Proxy-Frontend#1]
Hi trying to test this tool

but i was unable to log in because 
$token = $headers['Authorization']; 
is null maybe a issue with framework7 request

**Comment by pcca-matrix** [comment]
What's your webserver ? 

cause the  function "apache_request_headers()" is only supported when PHP is installed as an Apache module.

**Comment by joaquinabenza** [comment]
this is the array returned for apache_request_headers()

`{"Accept":"text\/html,application\/xhtml+xml,application\/xml;q=0.9,image\/webp,image\/apng,*\/*;q=0.8","Accept-Encoding":"gzip","Accept-Language":"es-ES,es;q=0.9,en;q=0.8","Cache-Control":"no-cache","Cf-Connecting-Ip":"xxx","Cf-Ipcountry":"ES","Cf-Ray":"xx","Cf-Visitor":"{\"scheme\":\"http\"}","Connection":"Keep-Alive","Cookie":"__cfduid=xx","Host":"xxx.com","Pragma":"no-cache","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","X-Forwarded-For":"xxx","X-Forwarded-Proto":"http"}`

There is no authorization key

**Comment by dorimanx** [comment]
Hi, please add to list that sqlite3 and sql server should be installed too.
and allow apache to work after install. :)

sudo apt-get install sqlite3 libsqlite3-dev
https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04

sudo ufw allow in "Apache Full"
sudo apt-get install mysql-server
follow the instructions.

only after configs for apache and install mysql-server + sqlite3 DB was created and proxy page works great.

Thanks!

**Comment by pcca-matrix** [comment]
@joaquinabenza
what is your server configuration ? unix , windows ? apache or IIS ?

@dorimanx 
mysql-server is not required  , only sqlite3  as mentioned in the readme.

**Comment by dorimanx** [comment]
ubuntu 16.04
ok, then only.
sudo apt-get install sqlite3 libsqlite3-dev
sudo ufw allow in "Apache Full"

**Comment by joaquinabenza** [comment]
Apache, its only a standard webhosting, not a VPS
Maybe i will try it on a VM to make it work beacuse i got issues with sqlite also
