### ISSUE TITLE
Do not build a graph as in the demo picture.

### ISSUE THREAD

**Issue by ORGaniZMo** [pcca-matrix/XMRig-Proxy-Frontend#2]
Checked for the latest versions of Chrome, IE and Firefox.

VDS/VPS, Ubuntu 16.04.4.
I installed everything according to the instructions.
Everything works, except for plotting.

The proxy works more than two days, if it is important.

**Comment by pcca-matrix** [comment]
In  php folder , do you have the proxy.db file  ? 

make sure you have proper write permissions for apache user

**Comment by ORGaniZMo** [comment]
![image](https://user-images.githubusercontent.com/25881599/39619185-4e9ce370-4fa0-11e8-8c50-679c5685c19e.png)

**Comment by pcca-matrix** [comment]
db is 0B size nothing is written inside.

is your crontask run every 5min  ?

**Comment by ORGaniZMo** [comment]
I did everything according to the instructions.

![image](https://user-images.githubusercontent.com/25881599/39619576-d4fb665c-4fa1-11e8-8de8-4c3870bfe80a.png)

**Comment by ORGaniZMo** [comment]
0,5,10,15,20,25,30,35,40,45,50,55 * * * * root /usr/bin/php /var/www/html/xmrig-proxy/php/cron.php
now is working

**Comment by pcca-matrix** [comment]
crontab -e should not have the root part, which specifies the username (crontab -e already edits a specific user's crontab).

If you want to run as root, do sudo crontab -e

*/5 * * * * /usr/bin/php /var/www/html/xmrig-proxy/php/cron.php

or create a file in /etc/cron.d

*/5 * * * * root /usr/bin/php /var/www/html/xmrig-proxy/php/cron.php
