### ISSUE TITLE
not working after updating ubuntu server from 16.04 lts to 18.04 lts

### ISSUE THREAD

**Issue by ORGaniZMo** [pcca-matrix/XMRig-Proxy-Frontend#6]
The database file and *.json are not created.
Until the server upgrade, everything worked. Where to find an error?
thx

**Comment by pcca-matrix** [comment]
it depends on apache and PHP not  your distro , 
it's a write permissions error
try
chown -R www-data:www-data  /path to your sqlite db

**Comment by ORGaniZMo** [comment]
Honestly, I already forgot about this problem. Today I checked - everything works without my intervention. Whatever Thank you.
