### ISSUE TITLE
There is no Hash rate chart

### ISSUE THREAD

**Issue by GjBrutello** [pcca-matrix/XMRig-Proxy-Frontend#7]
Hello! I have windows 10 and installed a server Nginx + PHP 7 module on it. Seems all works fine but the chart and changing config.json file not working, button Submit doesn't appear after fill any fields in page "XMRig-Proxy Settings". I use manually with cmd: 
`curl -v --data-binary @config.json -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer qwerty123" http://127.0.0.1:8080/1/config `
😁

<details>
<summary>Spoiler screenshot</summary>

![xmrig-prx](https://user-images.githubusercontent.com/50217444/108990114-a0e39580-76c0-11eb-8664-474ac5c1b642.png)

</details>

 Anyway Thanks for your great work.

**Comment by mthqwork** [comment]
@GjBrutello 
Make sure that you have enabled the SQLite3 module at php.ini. 
Look at developer tools, one of the get_json.php request will fail with HTTP 500.
As error reporting is exclusively disabled in get_json.php, you have to enable it, to see what's up. 
I had this: ` PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found`

**Comment by GjBrutello** [comment]
As you see there is proxy.db file so SQLite3 works. Just need to add request of cron.php in windows task schedule but I don't need in that hr graph .

<details>
<summary>Spoiler screenshot</summary>

![api3](https://user-images.githubusercontent.com/50217444/192121246-2edb3e89-3611-4a89-bf06-a5260aef055e.png)

</details>
